Dulwa.v1/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dulwa.v1.Service.DulwaInfo;
using Microsoft.AspNetCore.Mvc.Rendering;
using Dulwa.v1.ViewModel;
using Microsoft.AspNetCore.Identity;
using Dulwa.v1.Models;
using Dulwa.v1.Service.Storys;
using Dulwa.v1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using ReflectionIT.Mvc.Paging;

namespace Dulwa.v1.Controllers
{
    public class StoryController : Controller
    {
        private IDulwaInfoService _dulwainfoservice;
        private UserManager<ApplicationUser> _usermanager;
        private IStoryService _storyservice;
        private IFileUpload _fileupload;

        public StoryController(IDulwaInfoService Dulwainfoservice, UserManager<ApplicationUser> userManager, IStoryService storyservice,IFileUpload file)
        {
            _dulwainfoservice = Dulwainfoservice;
            _usermanager = userManager;
            _storyservice = storyservice;
            _fileupload = file;
        }
        public async Task<IActionResult> Index(int page=1)
        {
            var data = await _dulwainfoservice.GetDulwainfoWithStory();
            var model= PagingList.Create(data, 5, page);
            return View(model);
        }

        public async Task<IActionResult> StoryDetail(string Id)
        {
            if (Id == string.Empty)
            {
                return NotFound();
            }
            return View(await _storyservice.GetStoryDetailById(Id));
        }

        public async Task<IActionResult> StoryDetailList(string Id)
        {
            if (Id == string.Empty)
            {
                return NotFound();
            }
           
            return View(await _dulwainfoservice.GetDulwainfoWithStory(Id));
        }
        public IActionResult StoryList()
        {
            return View();
        }
        [Authorize]
        public async  Task<IActionResult> Create()
        {
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Create", "DulwaStory", new { area = "Admin" });
            }
            ViewData["DulwainfoId"] = new SelectList(await _dulwainfoservice.getDulwaInfo(), "Id", "Name");
            ViewData["StoryCateogory"] = new SelectList(await _storyservice.GetAllStoryCategory(), "Id", "Name");           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(StoryViewModel Model)
        {
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Create", "DulwaStory", new { area = "Admin" });
            }
            Model.Author = User.Identity.Name;
            Model.UserId = _usermanager.GetUserId(User);
            Model.Approval = false;
           await _storyservice.CreateStory(Model);
            return RedirectToAction("Story","User");
        }
        [HttpPost]
        [Route("api/images/upload")]
        public async Task<IActionResult> UploadImage()
        {
          return Ok(new {location= $"/content/uploaded/{await _fileupload.Upload(Request.Form.Files[0])}"});
        }
    }
}

Dulwa.v1/ViewComponents/SideBarViewComponent.cs
using Dulwa.v1.Service.Advertisements;
using Dulwa.v1.Service.Packages;
using Dulwa.v1.Service.Storys;
using Dulwa.v1.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dulwa.v1.ViewComponents
{
    public class SideBarViewComponent:ViewComponent
    {
        private IStoryService _storyservice;
        private IPackageService _packageservice;
        private IAdvertisementService _advertisementservice;

        public SideBarViewComponent(IStoryService storyservice, IPackageService packageservice, IAdvertisementService advertisementservice)
        {
            _storyservice = storyservice;
            _packageservice = packageservice;
            _advertisementservice = advertisementservice;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var SideBar = new SideBarListViewModel();
            SideBar.Story =await _storyservice.GetTopStory(4);
            SideBar.Package = await _packageservice.GetTopPackage(4);
            SideBar.Advertisement =await _advertisementservice.GetAdvertisementList(2);
            return View(SideBar);
        }
    }
}

Dulwa.v1/Views/Story/Create.cshtml
@model Dulwa.v1.ViewModel.StoryViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "_userlayout";
}
<link href="~/lib/Summernote/summernote.css" rel="stylesheet" />

<section class="details-content">
    <div class="jr-site-centralize ">
        <div class="">
            <div id="wrapper">
                <div id="page-content-wrapper">
                    <div class="panel panel-default">
                        <div class="panel-body bg-white">

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="section-title flex-box">
                                            <h1 class="font-large">Share your story</h1>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-1 col-xs-1">
                                                <img src="~/images/user_placeholder.png" class="img-circle img-responsive" />
                                            </div>
                                            <div class="col-md-4 col-xs-4">
                                               @User.Identity.Name<br />
                                                <span style="font-size:12px">dulwa.com</span><br />
                                                <span style="font-size:10px">Draft</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <form asp-action="Create" asp-controller="Story" method="post" enctype="multipart/form-data" id="my_form">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @*<label asp-for="Name" class="control-label"></label>*@
                                            <label class="control-label">Give a title to your story</label>
                                            <input asp-for="Name" class="form-control" />
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="StoryCategoryId" class="control-label"></label>
                                            <select asp-for="StoryCategoryId" class="form-control" asp-items="ViewBag.StoryCateogory"></select>
                                            <span asp-validation-for="StoryCategoryId" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="Date" class="control-label">Story Date</label>
                                            <input type="date" asp-for="Date" class="form-control" />
                                            <span asp-validation-for="Date" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="Link" class="control-label">Youtube Link</label>
                                            <input asp-for="Link" class="form-control" />
                                            <span asp-validation-for="Link" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="DulwainfoId" class="control-label"></label>
                                            <select asp-for="DulwainfoId" class="form-control" asp-items="ViewBag.DulwaInfoId"></select>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label asp-for="CoverImage" class="control-label"></label>
                                            <br />
                                             <a id="upfile1" style="cursor: pointer;">
                                                <img src="~/images/banner-placeholder.png" class="" id="previewimage" alt="img" style="width:100%;height:300px;" title="Click here to upload image" />
                                            </a>
                                            <input type="file" style="display:none;" id="CoverImage" name="CoverImage" onchange="$('#previewimage')[0].src = window.URL.createObjectURL(this.files[0])" /><!--onchange="$('#previewimage')[0].src = window.URL.createObjectURL(this.files[0])"-->

                                            <span asp-validation-for="CoverImage" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @*<label asp-for="Description" class="control-label"></label>*@
                                            <label class="control-label">Write some description about your story</label>
                                            <textarea asp-for="Description" class="form-control"></textarea>
                                        </div>
                                        <input name="image" type="file" id="upload" onchange="" style="display: none;">
                                        <div class="form-group">
                                            <input type="submit" value="Share Now" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</section>

@section Scripts{
    <script src="~/lib/Summernote/summernote.js"></script>
    <script>
        $(document).ready(function () {
            $('#Description').summernote({
                height: 300,
                popover: {
                    image: [],
                    link: [],
                    air: []
                }
            });
            $(function () { $("#upfile1").click(function () { $("#CoverImage").trigger('click'); }); })
        });
    </script>



}

Dulwa.v1/Views/Story/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<Dulwa.v1.ViewModel.DulwaInfoViewModel>
@using ReflectionIT.Mvc.Paging
@addTagHelper *, ReflectionIT.Mvc.Paging
@{
    ViewData["Title"] = "Index";
}
<div class="body-wrapp destination clearfix">
    <section class="d-banner banner-package clearfix flex-box" style="background-image: url('../../images/111.jpg')">
        <div class="package-title ">
            <div class="caption stories-banner-text text-align-center pd-l-40 pd-r-40">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <h1>
                                <span>Beautiful Stories</span>
                                <br> Covered by Dulwa
                            </h1>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <input type="text" style="padding:9px;" placeholder="Eg: Pokhara Portrait">
                                    <a href="#" class="custom-btn primary-btn">Browse</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <!--Details contente-->
    <section class="details-content">
        <div class="jr-site-centralize ">
            <div class="container-story">
                @*<div class="flex-box">*@
                <div class="row">
                    <div class="col-md-8 content-wrap col-8-padding-left">

                        <div class="flex-box justify-right">
                            <!--no stretch class-->

                            <div class="left-cont-wrapp storieslist">
                                <!--Category Start-->
                                @foreach (var story in Model)
                                {
                                    <div class="category-wrap">
                                        <div class="title">
                                            <div class="row">
                                                <div class="col-md-9">
                                                    <div class="form-group">
                                                        <h4>From the @story.Name</h4>
                                                    </div>
                                                </div>
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <a asp-action="StoryDetailList" asp-controller="Story" asp-route-id="@story.slug" class="custom-btn light-grey-btn pull-right">View all</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="stories-list row common-posts">
                                            @if (story.DulwaStory.Count > 0)
                                            {
                                                @foreach (var storydetail in story.DulwaStory.Select((value, index) => new { Value = value, Index = index }))
                                                {
                                                    @if (storydetail.Index == 0)
                                                    {
                                                        <div class="col-md-5">
                                                            <div class="item big">
                                                                <img src="~/Content/Uploaded/@storydetail.Value.ImageUrl" class="img-responsive">
                                                                <div class="info">
                                                                    <span class="category">@storydetail.Value.Name</span>
                                                                    <span class="authors">
                                                                        <span>
                                                                            <i class="ti-user"></i>@storydetail.Value.Author
                                                                        </span>
                                                                        <span>
                                                                            <i class="ti-calendar"></i>@storydetail.Value.Date.ToString("dd MM, yyyy")
                                                                        </span>
                                                                    </span>
                                                                    <a asp-action="Detail" asp-controller="Story" asp-route-id="@storydetail.Value.slug" class="title">@storydetail.Value.Name</a>

                                                                </div>
                                                            </div>
                                                        </div>
                                                        break;
                                                    }
                                                }

                                                <div class="col-md-7">
                                                    <div class="flex-box flex-wrap">
                                                        @foreach (var storydetail in story.DulwaStory.Select((value, index) => new { Value = value, Index = index }))
                                                        {
                                                            @if (storydetail.Index > 0)
                                                            {
                                                                <div class="col-md-6">
                                                                    <div class="item" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">
                                                                        <img src="~/Content/Uploaded/@storydetail.Value.ImageUrl" class="img-responsive">
                                                                        <div class="info">
                                                                            <span class="category">@storydetail.Value.Name</span>
                                                                            <span class="authors">
                                                                                <span>
                                                                                    <i class="ti-user"></i>@storydetail.Value.Author
                                                                                </span>
                                                                                <br />
                                                                                <span>
                                                                                    <i class="ti-calendar"></i>@storydetail.Value.Date.ToString("dd MM, yyyy")
                                                                                </span>
                                                                            </span>
                                                                            <a asp-action="Detail" asp-controller="Story" asp-route-id="@storydetail.Value.slug" class="title">@storydetail.Value.Name</a>

</div>
                                                                    </div>
                                                                </div>
                                                            }
                                                        }
                                                    </div>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="col-md-12">
                                                    <div class="item">
                                                        <img src="~/Content/Uploaded/@story.Image">
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                }
                                <!--Pagination-->
                                <nav aria-label="Suppliers navigation example">
                                    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
                                </nav>
                                <!--Pagination Ends-->
                            </div>

                        </div>

                    </div>
                    <div class="col-md-4 sidebar pd-t-80 pd-b-80 pd-l-40 pd-r-40">
                        <div class="create-story">
                            <a asp-action="Create" asp-controller="Story" class="custom-btn primary-btn">Share your Story</a>

                        </div>
                        @await Component.InvokeAsync("SideBar")

                    </div>
                </div>
            </div>
        </div>
    </section>





</div>

Dulwa.v1/Views/Story/StoryDetail.cshtml
@model Dulwa.v1.ViewModel.StoryViewModel
@{
    ViewData["Title"] = "StoryDetail";
}

<div class="body-wrapp destination clearfix">

    <!--Top Banner-->
    <section class="d-banner banner-package clearfix flex-box" style="background-image: url('../../Content/Uploaded/@Model.ImageUrl')">
        <div class="package-title ">

            <div class="caption stories-banner-text pd-l-40 pd-r-40">

                <div class="post-details-title flex-box">

                    <div class="author-img">
                        @if (Model.User.Profile != null)
    {
                    <img src="~/Content/Uploaded/@Model.User.Profile" alt="@Model.User.FullName"/>

}
else
{

                    <img src="~/images/user_placeholder.png" />

}
                    </div>
                    <div class="post-info">
                        <span class="category">@Model.StoryCategory.Name</span>
                        <h1>
                            <span>Beautiful Stories</span><br>
                            Covered by Dulwa
                        </h1>
                        <span class="authors">
                            <span><i class="ti-user"></i>@Model.Author</span>
                            <span><i class="ti-calendar"></i>@Model.Date.ToString("dd MMM, yyyy")</span>
                        </span>
                    </div>


                    <div class="nearest-desti d-i-b">
                        <span><i class="ti-location-pin"></i><a href="#">View Route</a></span>

                    </div>


                </div>

            </div>

        </div>
    </section>



    <!--Details contente-->
    <section class="details-content">
        <div class="jr-site-centralize ">
            <div class="container-story">
                <div class="row">
                    <div class="col-md-8 content-wrap pd-l-0 pd-r-0">
                        @if (Model.Link != null)
                        {
                            <p>@Model.Link</p>
                        <div class="post-details-page-main-video">
                            @{
                                var youtube = Model.Link.Split("v=");
                                var link = youtube[1].Split("&");
                            }
                            <iframe width="854" height="480" src="https://www.youtube.com/embed/@link[0]" frameborder="0" gesture="media" allowfullscreen></iframe>

                        </div>
                        }

                        <div class="flex-box justify-right col-8-padding-left">
                            <!--no stretch class-->

                            <div class="left-cont-wrapp">

                                <div class="big-text">
                                    @Model.Name
                                </div>
                                <p>
                                    @Html.Raw(Model.Description)
                                </p>
                                <div class="comment-section">
                                    <h2>Comments</h2>
                                    <div class="fb-comments" data-href="https://localhost:44397/Story/StoryDetail/@Model.Id" data-numposts="8"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 sidebar pd-t-80 pd-b-80 pd-l-40 pd-r-40">
                        <div class="create-story">
                            <a asp-action="Create" asp-controller="Story" class="custom-btn primary-btn">Share your Story</a>
                        </div>
                        @await Component.InvokeAsync("SideBar")


                    </div>
                </div>

            </div>
        </div>
    </section>
</div>

Dulwa.v1/Views/Story/StoryDetailList.cshtml
@model Dulwa.v1.ViewModel.DulwaInfoViewModel
@{
    ViewData["Title"] = "StoryDetailList";
}
<div class="body-wrapp destination clearfix">

    <section class="d-banner banner-package clearfix flex-box" style="background-image: url('../../Content/Uploaded/@Model.Image')">
        <div class="package-title ">
            <div class="caption stories-banner-text text-align-center flex-box pd-l-40 pd-r-40">
                <h1>
                    <span>Beautiful Stories</span><br>
                    Covered by Dulwa
                </h1>
            </div>
        </div>
    </section>

    <!--Details contente-->
    <section class="details-content">
        <div class="jr-site-centralize ">
            <div class="container-story">
                <div class="row">
                    <div class="col-md-8 content-wrap col-8-padding-left">
                        <div class="flex-box justify-right">
                            <!--no stretch class-->
                            <div class="left-cont-wrapp storieslist">
                                <!--Category Start-->
                                <div class="category-wrap cat-details-list">
                                    <div class="title flex-box">
                                        <h2>From the @Model.Name</h2>
                                    </div>

                                    <div class="stories-list row common-posts">
                                        @foreach (var story in Model.DulwaStory.Select((value, index) => new { Value = value, Index = index }))
                        {
                            if (story.Index == 0)
                            {
                                <div class="col-md-12">
                                    <div class="item big">
                                        <img src="~/Content/Uploaded/@story.Value.ImageUrl">
                                        <div class="info">
                                            <span class="category">@story.Value.StoryCategory.Name</span>
                                            <span class="authors">
                                                <span><i class="ti-user"></i>@story.Value.Author</span><br />
                                                <span><i class="ti-calendar"></i>@story.Value.Date.ToString("dd MMM, yyyy")</span>
                                            </span>
                                            <a asp-action="Detail" asp-controller="Story" asp-route-id="@story.Value.slug" class="title">

                                                @story.Value.Name
                                            </a>
                                        </div>
                                    </div>
                                </div>
                break;
            }
        }
                                        <div class="col-md-12">
                                            <div class="row flex-wrap">
                                                @foreach (var story in Model.DulwaStory.Select((value, index) => new { Value = value, Index = index }))
                                {
                                    if (story.Index > 0)
                                    {
                                        <div class="col-md-6">
                                            <div class="item">
                                                <img src="~/Content/Uploaded/@story.Value.ImageUrl">
                                                <div class="info">
                                                    <span class="category">@story.Value.StoryCategory.Name</span>
                                                    <span class="authors">
                                                        <span><i class="ti-user"></i>@story.Value.Author</span><br />
                                                        <span><i class="ti-calendar"></i>@story.Value.Date.ToString("dd MMM, yyyy")</span>
                                                    </span>
                                                    <a asp-action="Detail" asp-controller="Story" asp-route-id="@story.Value.slug" class="title">
                                                        @story.Value.Name
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                    }
                }
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <!--Category Ends-->

                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 sidebar pd-t-80 pd-b-80 pd-l-40 pd-r-40">
                        <div class="create-story">
                            <a asp-action="create" asp-controller="story" class="custom-btn primary-btn">Share your Story</a>
                        </div>
                        @await Component.InvokeAsync("SideBar")

                    </div>
                </div>
            </div>
        </div>
    </section>

</div>