Dulwa.v1/Areas/Admin/Controllers/DulwaInfoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dulwa.v1.Service.DulwaInfo;
using Dulwa.v1.ViewModel;
using Dulwa.v1.Services;
using Microsoft.AspNetCore.Authorization;
using Dulwa.v1.Service.KeyCategories;
using Microsoft.AspNetCore.Mvc.Rendering;
using Dulwa.v1.Data;
using System;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace Dulwa.v1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DulwaInfoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IDulwaInfoService _dulwaservice;
        private IFileUpload _file;
        private IKeyCategoryService _categoryservice;

        public DulwaInfoController(IDulwaInfoService dulwaservice, IFileUpload file,IKeyCategoryService categoryservice)
        {
            _dulwaservice = dulwaservice;
            _file = file;
            _categoryservice = categoryservice;
        }
        public async Task<IActionResult> Index()
        {            
            return View(await _dulwaservice.getDulwaInfo());
        }

        // GET: Admin/Company/Details/5
        public async Task<IActionResult> Details()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            ViewData["type"] = new SelectList( await _categoryservice.GetKeys("Type"),"Id","Name");
            ViewData["popular"] = new SelectList( await _categoryservice.GetKeys("Popular"),"Id","Name");
            ViewData["season"] = new SelectList( await _categoryservice.GetKeys("Season"),"Id","Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DulwaInfoViewModel Model)
        {
            if (ModelState.IsValid)
            {
              Model.Image=await _file.Upload(Model.File);               
                
              var destination= await _dulwaservice.createDulwaInfo(Model);
                return RedirectToAction("DulwainfoRouteCreate","Route",new { Id=destination.Id});
            }
            ViewData["type"] = new SelectList(await _categoryservice.GetKeys("Type"), "Id", "Name");
            ViewData["popular"] = new SelectList(await _categoryservice.GetKeys("Popular"), "Id", "Name");
            ViewData["season"] = new SelectList(await _categoryservice.GetKeys("Season"), "Id", "Name");
            return View(Model);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dulwainfo = await _dulwaservice.GetSingleData(id);
            ViewData["type"] = new SelectList(await _categoryservice.GetKeys("Type"), "Id", "Name");
            ViewData["popular"] = new SelectList(await _categoryservice.GetKeys("Popular"), "Id", "Name");
            ViewData["season"] = new SelectList(await _categoryservice.GetKeys("Season"), "Id", "Name");
            if (dulwainfo == null)
            {
                return NotFound();
            }
            return View(dulwainfo);
        }

        // POST: Admin/Event/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]        
        public async Task<IActionResult> Edit(Guid id, DulwaInfoViewModel Model)
        {
            if (id != Model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _dulwaservice.EditDulwaInfo(Model);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await _dulwaservice.CheckData(Model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }           
            return View(Model);
        }


        [HttpPost]
        public async Task<JsonResult> Delete(Guid id)
        {
            try
            {
                await _dulwaservice.DeleteDulwaInfo(id);
                return Json(HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                return Json(HttpStatusCode.InternalServerError);
            }

        }




    }
}

Dulwa.v1/Areas/Admin/Views/DulwaInfo/Create.cshtml
@model Dulwa.v1.ViewModel.DulwaInfoViewModel

@{
    ViewData["Title"] = "Create";
}
<!--Modified view-->
<h4>Create New Destination</h4>
<div class="card padding-20">
    Please fill up all the requirement fields
</div>
<hr />
<div class="row" ng-controller="MapFullController">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Types" class="control-label"></label>
                <select asp-for="Types" class="form-control multiple" asp-items="ViewBag.type" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <label asp-for="populars" class="control-label"></label>
                <select asp-for="populars" class="form-control multiple" asp-items="ViewBag.popular" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <label asp-for="seasons" class="control-label"></label>
                <select asp-for="seasons" class="form-control multiple" asp-items="ViewBag.season" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label><br />
                <img src="~/images/default_image.png" class="userimg img-circle img-thumbnail" id="previewimage" alt="img">
                <br /><br />
                <div class="waves-effect waves-light">
                    <input type="file" class="upload" name="File" onchange="$('#previewimage')[0].src = window.URL.createObjectURL(this.files[0])" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Lat" class="control-label"></label>
                <input ng-model="mapLat" asp-for="Lat" class="form-control" />
                <span asp-validation-for="Lat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lon" class="control-label"></label>
                <input ng-model="mapLong" asp-for="lon" class="form-control" />
                <span asp-validation-for="lon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div ng-click="LoadMapData()" class="days-out text-align-center pd-t-80 pd-t-80 pd-l-40 pd-r-40 col-md-8" id="map-canvas" style="width:100%;height:500px;" ng-init="LoadMap()">
    </div>
</div>
@section scripts{
    <script src="~/AngularServices/Services/mapServices.js"></script>
    <script src="~/AngularServices/Controllers/mapFullController.js"></script>
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />
    <script src="~/lib/select2/js/select2.js"></script>
    <script>
        $(document).ready(function () {
            $('.multiple').select2();
        });
    </script>
}

Dulwa.v1/Areas/Admin/Views/DulwaInfo/Delete.cshtml
@model Dulwa.v1.ViewModel.DulwaInfoViewModel

@{
    ViewData["Title"] = "Delete";
}
<!--Modified view-->
<div class="panel text-center">
    <h2>Are you sure you want to delete this?</h2>
    <div>
        <center>
            <a href="~/Content/Uploaded/ @Html.DisplayFor(model => model.Image))" target="_blank">
                <img src="~/Content/Uploaded/@Html.DisplayFor(model => model.Image)" class="admin-table-image" />
            </a>
        </center>
        <h4> @Html.DisplayFor(model => model.Name)</h4>
        <hr />
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <a asp-action="Index" class="btn btn-primary">Back to List</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Dulwa.v1/Areas/Admin/Views/DulwaInfo/Details.cshtml
@{
    ViewData["Title"] = "Details";
}
<!--Modified view-->
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6 card">
                <div class="form-group">
                    <img src="~/Content/Uploaded/05042018-16032018-16032018-package3.png" width="100%" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <table class="table">
                        <tr>
                            <td colspan="2">
                                <h3>Dulwa Info Details</h3>
                            </td>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>test123</td>
                        </tr>
                        <tr>
                            <td>Address</td>
                            <td>address123</td>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>test123</td>
                        </tr>
                        @*<tr>
                <td></td>
                <td>
                    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.Id">Edit</a>
                    <a asp-action="Index" class="btn btn-success">Back to List</a>
                </td>
            </tr>*@
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <img src="~/images/mustangImg.png" class="img-responsive img-mid-height" style="opacity: 1">
                </div>
                <div class="form-group">
                    <center>
                        <span>
                            <button type="button" class="product-button btn-dark"><span>Detail</span></button>
                        </span>
                    </center>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <img src="~/images/mustangImg.png" class="img-responsive img-mid-height" style="opacity: 1">
                </div>
                <div class="form-group">
                    <center>
                        <span>
                            <button type="button" class="product-button btn-dark"><span>Detail</span></button>
                        </span>
                    </center>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <img src="~/images/mustangImg.png" class="img-responsive img-mid-height" style="opacity: 1">
                </div>
                <div class="form-group">
                    <center>
                        <span>
                            <button type="button" class="product-button btn-dark"><span>Detail</span></button>
                        </span>
                    </center>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <img src="~/images/mustangImg.png" class="img-responsive img-mid-height" style="opacity: 1">
                </div>
                <div class="form-group">
                    <center>
                        <span>
                            <button type="button" class="product-button btn-dark"><span>Detail</span></button>
                        </span>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>

Dulwa.v1/Areas/Admin/Views/DulwaInfo/Edit.cshtml
@model Dulwa.v1.ViewModel.DulwaInfoViewModel

@{
    ViewData["Title"] = "Edit";
}
<!--Modified view-->
<h4>Create New Dulwa Info</h4>
<div class="card padding-20">
    Please fill up all the requirement fields
</div>
<hr />
<div class="row" ng-controller="MapFullController">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Types" class="control-label"></label>
                <select asp-for="Types" class="form-control multiple" asp-items="ViewBag.type" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <label asp-for="populars" class="control-label"></label>
                <select asp-for="populars" class="form-control multiple" asp-items="ViewBag.popular" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <label asp-for="seasons" class="control-label"></label>
                <select asp-for="seasons" class="form-control multiple" asp-items="ViewBag.season" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label><br />
                <img src="~/Content/Uploaded/@Model.Image" class="userimg img-circle img-thumbnail" id="previewimage" alt="img">
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" class="form-control" onchange="$('#previewimage')[0].src = window.URL.createObjectURL(this.files[0])" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lat" class="control-label"></label>
                <input ng-model="mapLat" asp-for="Lat" ng-init="mapLat=@Model.Lat" class="form-control" />
                <span asp-validation-for="Lat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lon" class="control-label"></label>
                <input ng-model="mapLong" asp-for="lon" ng-init="mapLong=@Model.lon" class="form-control" />
                <span asp-validation-for="lon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Image" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div ng-click="LoadMapData()" class="days-out text-align-center pd-t-80 pd-t-80 pd-l-40 pd-r-40 col-md-8" id="map-canvas" style="width:100%;height:500px;" ng-init="LoadMap()">
    </div>
</div>
@section scripts{
    <script src="~/AngularServices/Services/mapServices.js"></script>
    <script src="~/AngularServices/Controllers/mapFullController.js"></script>
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />
    <script src="~/lib/select2/js/select2.js"></script>
    <script>
        $(document).ready(function () {
            $('.multiple').select2();
        });
    </script>
}

Dulwa.v1/Areas/Admin/Views/DulwaInfo/Index.cshtml
@model IEnumerable<Dulwa.v1.ViewModel.DulwaInfoViewModel>

@{
    ViewData["Title"] = "Index";
}
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}
<!--Modified view-->
<div class="form-group table-responsive">
    <table id="myTable" class="table table-hover" style="display:none">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Rating)
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>*@

                <th>
                    @Html.DisplayNameFor(model => model.Lat)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.lon)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a href="~/Content/Uploaded/@Html.DisplayFor(modelItem => item.Image)" target="_blank">
                            <img src="~/Content/Uploaded/@Html.DisplayFor(modelItem => item.Image)" class="admin-table-image" />
                        </a>

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rating)
                    </td>
                    @*<td>
                            <span class="text-no-wrap"> @Html.DisplayFor(modelItem => item.Description)</span>
                        </td>*@

                    <td>
                        @Html.DisplayFor(modelItem => item.Lat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lon)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        <a href="" class="Delete" data-id="@item.Id">Delete</a>
                        <input type="hidden" name="__RequestVerificationToken" id="__RequestVerificationToken" value="@GetAntiXsrfRequestToken()" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="row" id="address-loading-placeholder">
    <div class="col-md-1 col-xs-3"><div class="loader loader-blue"></div></div>
    <div class="col-md-3 col-xs-9">Loading Data...</div>
</div>
<br /><br />
<div class="row">
    <div class="col-md-6">
        <a class="btn btn-primary" asp-action="Create" asp-controller="DulwaInfo"><i class="fa fa-plus"></i> Add New</a>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $('#address-loading-placeholder').fadeOut(3000, function () {
                $('#myTable').fadeIn();
            });
            $('#myTable').DataTable({
                "order": [[0, "asc"]]
            });           
            $('.Delete').on('click', function () {
                console.log("this is test");
                var id = $(this).data("id");
                var token = $('#__RequestVerificationToken').val();
                var myData = { id: id };
                var dataWithAntiforgeryToken = $.extend(myData, { '__RequestVerificationToken': token });
                swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this imaginary file!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                    .then((willDelete) => {
                        if (willDelete) {
                            $.ajax({
                                url: "/admin/dulwainfo/delete",
                                method: "Post",
                                data: dataWithAntiforgeryToken,
                                success: function (res) {
                                    if (res == 200) {
                                        swal("Your data has been deleted!", {
                                            icon: "success",
                                        }).then((value) => {
                                            location.reload();
                                        });
                                    }
                                    else {
                                        swal("Your data cannot be deleted!", {
                                            icon: "error",
                                        })
                                    }
                                }
                            })

                        }
                    });
            });
        });
    </script>
}